-- Your SQL goes here-- Your SQL goes here
CREATE TABLE words (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  word VARCHAR NOT NULL,
  meaning VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  example TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 'f'
);

CREATE TABLE encounters (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  word VARCHAR NOT NULL,
  timestamp BIGINTEGER NOT NULL,
  source VARCHAR NOT NULL
)
